stages:
  - test
  - build

variables:
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA

test:
  stage: test
  image: python:3.11
  before_script:
    - pip install -r requirements.txt
  script:
    - pytest
  only:
    - main

build:
  stage: build
  image: docker:latest
  services:
    - docker:dind

  script:
    - echo "Login GitLab Registry"
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

    - echo "Build image"
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .

    - echo "Push image"
    - docker push $IMAGE_NAME:$IMAGE_TAG

  only:
    - main
